# Generated by Django 5.0.9 on 2024-10-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sorsore", "0041_landingpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="layoutsettings",
            name="choose_template",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
